### ISSUE TITLE
关于zerorpc

### ISSUE THREAD

**Issue by GeorgeLZH0913** [obsession707/DIP#1]
项目的electron文件夹内没有node_modules文件夹，请问你现在还能找到这个项目的node_modules吗？
我在安装配置zerorpc时也遇到了问题，按你提到的那个electron-python-example项目也没成功。

**Comment by Rehoni** [comment]
尴尬，现在已经没有了。当时好像也没有传上来...你看看readme里的解决方案呢，当时我还参照了这个https://github.com/fyears/zerorpc-node，也可以试试看

**Comment by GeorgeLZH0913** [comment]
你这个项目当时有打包成exe吗，现在还能找到吗？

**Comment by Rehoni** [comment]
sry，换了电脑找不到啦
